### ISSUE TITLE
Issues in ContextualMenu docs (Storybook)

### ISSUE THREAD

**Issue by lorumic** [canonical/react-components#1033]
I was browsing the docs for the `ContextualMenu` component and I noticed a few issues:

![Peek 2024-01-30 16-06](https://github.com/canonical/react-components/assets/56583786/66b3b5f7-0687-498f-87d8-dc6dfecc1617)

Not sure that the one in the "Overflowing container" example is a real issue, but I guess the errors in the 2 examples at the bottom should be addressed.

Leaving this here for anyone who might know how to fix it and/or have time to do it - feel free to assign yourself. :)

**Comment by rsmelo92** [comment]
Hello I opened a small PR to fix this, https://github.com/canonical/react-components/pull/1037
