### ISSUE TITLE
Textarea doesn't update value when it's an empty string

### ISSUE THREAD

**Issue by andesol** [canonical/react-components#1068]
Consider this simplified example:

```js
import { useState } from 'react';
import { Button, Textarea } from "@canonical/react-components";

function App() {
  const [data, setData] = useState("Default text");

  return (
      <div>
        <Button onClick={() => setData("")}>
          Show nothing
        </Button>
        <p>Current data is: {data}</p>
        <Textarea
          value={data}
          onChange={(e) => setData(e.target.value)}
        />
      </div>
    );
}
```

This is the default scenario:

![image](https://github.com/canonical/react-components/assets/20623084/9dd66d91-a8b7-499f-9874-240edf0fcde4)

I'd expect clicking the button to clear the value in the `Textarea`. However, while the state is correctly updated (to an empty string), the `Textarea` still shows the previous value.

![image](https://github.com/canonical/react-components/assets/20623084/9e7bd8b6-f9a9-4fa6-ab45-e74bc32a38ac)

**Comment by andesol** [comment]
It looks like [this line](https://github.com/canonical/react-components/blob/main/src/components/Textarea/Textarea.tsx#L162) should be
```
props.value ?? innerValue
```

**Comment by bartaz** [comment]
Good catch @andesol. Care to propose a PR? I guess it would be good to have a test case that catches this as well.

**Comment by andesol** [comment]
@bartaz Indeed, here's the PR https://github.com/canonical/react-components/pull/1070
