### ISSUE TITLE
EmptyState implementation inconsistency with Vanilla Framework

### ISSUE THREAD

**Issue by vladimir-cucu** [canonical/react-components#1071]
Vanilla Framework's design of `EmptyState` component can be found [here](https://vanillaframework.io/docs/patterns/empty-state#no-content) and the `react-components` library's design can be found [here](https://canonical.github.io/react-components/?path=/docs/emptystate--docs). The image is rendered to the left of the text in Vanilla Framework, while it is rendered on top of the text in `react-components` library.

**Comment by vladimir-cucu** [comment]
Had a small chat today with @lukasSerelis and he specified that the Empty State design from Vanilla Framework is the one we should use in the web apps as well.

**Comment by bartaz** [comment]
Thanks for confirming that. I'm not sure why this inconsistency was introduced, but will be good to fix that to avoid confusion.

**Comment by vladimir-cucu** [comment]
@bartaz I'm currently looking into how Vanilla Framework implemented the [Empty State](https://vanillaframework.io/docs/patterns/empty-state) and the implementations of all 3 types of Empty States differ. Are we only concerned with implementing the [No content Empty State](https://vanillaframework.io/docs/patterns/empty-state#no-content) in this component?

**Comment by bartaz** [comment]
Yes, the Vanilla docs for Empty State pattern are very generic and cover variety of cases (search, 404, etc). For apps the most relevant is "no content" empty state, so that was meant to be covered by this React component.

**Comment by bartaz** [comment]
Also note that this is very context specific, so image may be different, text obviously. The action button also should be optional.

<img width="1119" alt="image" src="https://github.com/canonical/react-components/assets/83575/688507a1-984d-4a2a-b0e6-cac7fe50fae7">

**Comment by jmuzina** [comment]
Closing as completed in #1076
