### ISSUE TITLE
Tooltip does not disappear when hovering over another tooltip in the same component

### ISSUE THREAD

**Issue by lorumic** [canonical/react-components#1073]
When there are multiple tooltips in the same component, hovering away from one and over another causes to keep both of them visible, as shown in the screenshots below:

![image](https://github.com/canonical/react-components/assets/56583786/75638dd6-1788-4f6c-b127-5db4144014d1)

![image](https://github.com/canonical/react-components/assets/56583786/273f0e34-49d8-4fc5-870c-f5b244f18772)

**Comment by edlerd** [comment]
This turned out to be a problem with running timers in the background, not so much about using multiple tooltips in on page. See linked PR.

**Comment by lorumic** [comment]
> This turned out to be a problem with running timers in the background, not so much about using multiple tooltips in on page. See linked PR.

It doesn't seem to happen when you have only 1 tooltip in the same page/component. So the description is correct (and the description is not about the *reason* of the bug, it's just a description of it).
