### ISSUE TITLE
Add a way to use the newer tag logo in the side navigation

### ISSUE THREAD

**Issue by steverydz** [canonical/react-components#1114]
Currently the application layout supports the old style logo which is an icon next to the word mark. Most of our sites and applications are now moving to using the tag style logo (see screenshot below).

This isn't specifically a problem with the React component as it comes straight from the [Vanilla component](https://vanillaframework.io/docs/layouts/application), however it's not possible to customise/override the logo in this component. Perhaps having an option to enable the tag style icon would be a solution to this?

![app-layout-logo](https://github.com/user-attachments/assets/09c07204-3b8c-4b0e-a2e1-9f528b689e6f)

**Comment by huwshimi** [comment]
The current workaround is to pass a ReactNode that contains the logo to the `logo` prop. You can see how we do this in Juju Dashboard:

https://github.com/canonical/juju-dashboard/blob/b3fb186bef033f07526dd42e5249737488fb6cd9/src/layout/BaseLayout/BaseLayout.tsx#L61-L66

The related issue in Vanilla: https://github.com/canonical/vanilla-framework/issues/5014.

**Comment by steverydz** [comment]
@huwshimi Thanks, that's helpful. I've tried that and it works. I'll close this issue.
