### ISSUE TITLE
Custom filters appear differently after refresh

### ISSUE THREAD

**Issue by hatched** [canonical/react-components#343]
If you type in a custom input value then refresh the page the pill has a prefix `CUSTOM` vs no prefix when initially entered.

![Screen Shot 2020-11-19 at 9 59 03 PM](https://user-images.githubusercontent.com/532033/99756337-8773f180-2ab2-11eb-93a9-09e09e83cf42.png)

**Comment by bartaz** [comment]
Cannot reproduce anymore.
