### ISSUE TITLE
Add components for application layout

### ISSUE THREAD

**Issue by bartaz** [canonical/react-components#420]
Build components that can be used to build application layout with side navigation, panels, etc.

**Comment by anthonydillon** [comment]
How do you plan to build this? Sounds like we need a global context that will re-render the layout components (side-navigation, panels, layout container etc).

**Comment by bartaz** [comment]
We talked about it with @anthonydillon and we think it would be a good idea to catch up at some point to discuss how application layout is implemented currently in React in JAAS dashboard and if we should build it in React components.

/cc @hatched @huwshimi @Caleb-Ellis 

TODO:

@bartaz to schedule something or start discussion over email
