### ISSUE TITLE
Modal requires title

### ISSUE THREAD

**Issue by hatched** [canonical/react-components#65]
It would be nice if the Modal didn't require a title when you want to use it to display something like an image.

**Comment by bartaz** [comment]
Vanilla CSS seems to require existence of title, so we would need to update there first.

**Comment by clagom** [comment]
@hatched is this still relevant? WG couldn't think of a valid use-case to have a modal without a title.

**Comment by hatched** [comment]
When expanding the bundle/model visualization in the Juju Dashboard we use a modal to house the visualization. In the image below you can see that the title of the modal is unnecessary but we'd have to resort to hacks to hide it so it's been left in. 

![Screen Shot 2022-01-12 at 9 34 44 AM](https://user-images.githubusercontent.com/532033/149171327-a465423d-6832-4a26-89a4-d5310e34647e.png)

**Comment by clagom** [comment]
WG: we should have different flavours:
- True modal, with [ ok ] [ cancel ] no close button
- No title, close button
- Title and close button
- Title and true modal with [ ok ] [ cancel ] and no close button

**Comment by anasereijo** [comment]
@clagom reading your comment above but can't find any use-case for the "True modal, with [ ok ] [ cancel ] no close button" which I believe is without a title - are you aware of any examples?

for the context you can see my [specs](https://docs.google.com/document/d/1YMj0CiMBeOqGP9IoxitbgFZImHf0Bxcr3CngLpAbzrQ/edit?usp=sharing) - still WIP

**Comment by anasereijo** [comment]
ready for a UX review - @wgx @danielmutis can you have a look, please?

@clagom left you a comment

**Comment by clagom** [comment]
Thanks @anasereijo, I think it's a good first draft and I saw @wgx reviewed it as well. I would just make sure we are not overlooking use cases and requirements from other products/websites. Did you include the broader team in this sense?

**Comment by elioqoshi** [comment]
@anasereijo did a few comments, I think there are some changes needed and still an open query from @clagom so we should resolve that before closing this.

**Comment by danielmutis** [comment]
I have reviewed the document and I think it's ready. We are only missing visual design.

**Comment by bartaz** [comment]
Seems that in React component title is not required anymore.
