### ISSUE TITLE
Tooltip adds 1px to page size when hidden

### ISSUE THREAD

**Issue by Caleb-Ellis** [canonical/react-components#764]
While hidden, the `Tooltip` component has the `u-off-screen` class that makes its height 1px. In MAAS we set a minimum height of 100vh on the body in order to push the footer to the bottom. This combination means that if there is a `Tooltip` on the page, there will always be a scrollbar of at least 1px regardless of how much content is on the page.

**Comment by petermakowski** [comment]
Will be fixed by https://github.com/canonical/vanilla-framework/pull/4554
