### ISSUE TITLE
No option to add a hidden table caption

### ISSUE THREAD

**Issue by steverydz** [canonical/react-components#854]
It's useful for screen readers if a table has a caption, however it's not always desirable for the caption to be visible to sighted users. See https://www.w3.org/WAI/tutorials/tables/caption-summary/

**Comment by petermakowski** [comment]
I second this, would be great to be able to customise props of the `emptyStateMsg`. Ideally we should be able to completely control the render output of this and disable any wrappers. This could be done via render prop pattern.
