### ISSUE TITLE
Move docs out of main

### ISSUE THREAD

**Issue by huwshimi** [canonical/react-components#944]
To simplify releasing the package we should move docs to a different branch and remove them from main.

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

We'll need to investigate only updating the docs when a new release is created.

**Comment by bartaz** [comment]
Had a quick look and yes, configuring different branch is trivial:

<img width="887" alt="image" src="https://github.com/canonical/react-components/assets/83575/2acb3053-c274-43d1-aae9-930b44f4e7c1">

But we would need to have a workflow that pushes to that branch on release, but…

It seems that you don't even need to host your static code anymore, as you can use github actions to deploy:

<img width="968" alt="image" src="https://github.com/canonical/react-components/assets/83575/4ee816aa-644b-4525-b0be-3488044846ca">


Quite possibly all we need is to use the https://github.com/actions/deploy-pages action in our release workflow, but I didn't fully investigate how it works.
