### ISSUE TITLE
Missing lodash/isEqual dep

### ISSUE THREAD

**Issue by huwshimi** [canonical/react-components#990]
This package now requires `lodash/isEqual` but it is not included in the deps.

**Comment by akmittal** [comment]
This looks like a small change. Everything seem to work because `lodash` is still there as dependency of other packages.
Can I work on this?

**Comment by huwshimi** [comment]
> Can I work on this?

@akmittal thanks for asking, but I actually created [a PR](https://github.com/canonical/react-components/pull/993) for this, but forgot to assign and link this issue.
